### ISSUE TITLE
test-lang examples do not work.

### ISSUE THREAD

**Issue by SpideyZac** [Isible/citadel#8]
I have tried all the examples from the test-lang/examples. Only 1 of them seems to get past the compiler, parser-test.tl, but when trying to use NASM on the output assembly, I receive this error:

PS D:\Users\zacml\dev\LOLCatCompiler\citadel\crates\test-lang> nasm -f elf64 -o main.o out.asm
out.asm:11: error: operation size not specified
PS D:\Users\zacml\dev\LOLCatCompiler\citadel\crates\test-lang> nasm -f bin -o main.o out.asm  
out.asm:11: error: impossible combination of address sizes

I would really like to use this project for my compiler but am trying to determine if it will actually work before implementing it in my code. I don't really want to use LLVM either as it's too big for my likings. Please tell me this is a fluke, or I will have to go write my own IR which I really don't want to do. I would also like to say this looks like a very cool and interesting project and I would like to see it continued as I understand it is not production level yet.

**Comment by Thepigcat76** [comment]
Hey, thanks for your interest in this project. Unfortunately it is still quite early and while the apis do exist, we have neither proper codegen or optimizations. I strongly recommend you to not use this yet, instead I would suggest something like cranelift.

**Comment by Thepigcat76** [comment]
Wait, do you just need the IR? Because if so, you might actually be able to use this... Could you maybe contact me on discord? my user name is: thepigcat

I also fixed the parser-test.tl file

**Comment by SpideyZac** [comment]
Sent request
